sudo: false
language: python
python:
  - "2.7"
cache:
  - pip
install:
  - pip install -r requirements/whitelabel.txt
# command to run tests
script:
  - paver install_pages
  - pep8 regression/
  - pylint regression/
