---
- name: saucelabs | install Java
  apt: pkg=openjdk-7-jdk state=present update_cache=yes

- name: saucelabs | download Sauce connect
  get_url: url={{ sauce_connect_url }} dest=/tmp/{{ sauce_zip }}

- name: saucelabs | unzip Sauce connect
  command:
    unzip /tmp/{{ sauce_zip }} -d /tmp/sauce creates=/tmp/sauce

- name: saucelabs | install Sauce connect
  command:
    cp /tmp/sauce/{{ sauce_jar }} /usr/local/bin/{{ sauce_jar }}
    creates=/usr/local/bin/{{ sauce_jar }}
