---
- name: selenium | Install system packages
  apt: pkg={{','.join(selenium_pkgs)}}
       state=present update_cache=yes

- name: selenium | Install Selenium server
  get_url: url={{ selenium_jar_url }} dest={{ selenium_jar_path }}
  tags:
    - selenium_grid

- name: selenium | Install Selenium node config
  copy: src=selenium_node.json dest={{ node_config_path }}
  tags:
    - selenium_grid

- name: selenium | Create hub upstart script
  template: src=selenium_hub.conf.j2 dest=/etc/init/selenium_hub.conf
  tags:
    - selenium_grid

- name: selenium | Create node upstart script
  template: src=selenium_node.conf.j2 dest=/etc/init/selenium_node.conf
  tags:
    - selenium_grid

- name: selenium | Google Chrome apt key
  apt_key: url={{ chrome_apt_key }} state=present

- name: selenium | Google Chrome apt repo
  apt_repository: repo='deb {{ chrome_apt_repo }} stable main'

- name: selenium | Install Google Chrome
  apt: pkg=google-chrome-stable state=present update_cache=yes

- name: selenium | Install ChromeDriver
  get_url: url={{ chromedriver_url }}
           dest=/var/tmp/chromedriver_{{ chromedriver_version }}.zip

- name: selenium | Install ChromeDriver 2
  shell: unzip /var/tmp/chromedriver_{{ chromedriver_version }}.zip
         chdir=/var/tmp

- name: selenium | Install ChromeDriver 3
  shell: mv /var/tmp/chromedriver /usr/local/bin/chromedriver

- name: selenium | Install Chromedriver 4
  file: path=/usr/local/bin/chromedriver mode=0755

- name: selenium | Restart selenium hub
  service: name=selenium_hub state=restarted
  tags:
    - selenium_grid

- name: selenium | Wait for selenium hub
  wait_for: port={{ selenium_hub_port }} delay=2 state=started
  tags:
    - selenium_grid

- name: selenium | Restart selenium node
  service: name=selenium_node state=restarted
  tags:
    - selenium_grid
