# Install helpful things for developing/debugging tests
---

# This will install the GUI and some other nice things
- name: dev | install system packages
  apt: pkg={{','.join(dev_pkgs)}}
       state=present update_cache=yes

- name: dev | create terminal theme dir
  file:
    path={{ terminalrc_dir }} state=directory
    owner={{ dev_user }} group={{ dev_group }} mode=700

- name: dev | install terminal theme
  get_url:
    url={{ terminalrc_url }} dest={{ terminalrc_dir }}/terminalrc
    owner={{ dev_user }} group={{ dev_group }} mode=700

- name: dev | create start directory
  file:
    path={{ start_dir }} state=directory
    owner="{{ dev_user }}" group="{{ dev_group }}" mode=700

- name: dev | install startup script
  template:
     src=startup.sh.j2 dest={{ dev_home }}/startup.sh
     owner={{ dev_user }} group={{ dev_group }} mode=700

- name: dev | ensure .bashrc exists
  command: touch {{ dev_home }}/.bashrc

- name: dev | add startup script to .bashrc
  lineinfile:
    dest={{ dev_home }}/.bashrc
    regexp="^source {{ dev_home }}/startup.sh"
    line="source {{ dev_home }}/startup.sh"

- name: dev | install virtualenv
  pip: name=virtualenv state=latest

- name: dev | create the virtualenv
  sudo_user: "{{ dev_user }}"
  command: /usr/local/bin/virtualenv {{ virtualenv }}

- name: dev | install E2E python requirements
  sudo_user: "{{ dev_user }}"
  pip:
    requirements={{ repo_dir }}/requirements.txt
    virtualenv={{ virtualenv }}
    virtualenv_command=/usr/local/bin/virtualenv

- name: dev | git clone edx/configuration
  git: repo={{ edx_config_repo }} dest={{ edx_config_path }}

- name: dev | install helper scripts
  copy:
    src=${item} dest={{ start_dir }}/${item}
    owner={{ dev_user }} group={{ dev_group }} mode=700
  with_items:
    - jenkins_env
    - start_sauce.sh
